version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "26.48.28.173:9000:9000"
      - "26.48.28.173:9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecret
    volumes:
      - "//e/minio-data:/data"
    command: server /data --console-address ":9001"
    
  clamav:
    image: clamav/clamav:latest
    ports:
      - "26.48.28.173:3310:3310"
    restart: always

volumes:
  minio-data: